#!/bin/sh

# move juci-broadcom-wl plugin to juci-wireless
sed -i "s/juci-broadcom-wl/juci-wireless/g" /etc/config/juci
sed -i "s/juci-broadcom-wl/juci-wireless/g" /etc/config/rpcd

# convert from old style juci ubus objects to new style juci ubus objects
sed -i "s/ubus:\/juci\/network\.status/ubus:router\.net/g" /etc/config/juci
sed -i "s/ubus:\/juci\/network/ubus:router\.net/g" /etc/config/juci
sed -i "s/ubus:\/juci\/system\.process/ubus:router.system->processes/g" /etc/config/juci
sed -i "s/ubus:\/juci\/system/ubus:juci\.system/g" /etc/config/juci
sed -i "s/ubus:\/juci\/upnpd/ubus:juci\.upnpd/g" /etc/config/juci
sed -i "s/ubus:\/juci\/wireless/ubus:juci\.wireless/g" /etc/config/juci
sed -i "s/ubus:\/juci\/diagnostics/ubus:juci\.diagnostics/g" /etc/config/juci
sed -i "s/ubus:\/juci\/speedtest/ubus:juci\.speedtest/g" /etc/config/juci

# convert from old style router ubus objects to new style router ubus objects
sed -i "s/ubus:router->info/ubus:router.system->info/g" /etc/config/juci
sed -i "s/ubus:router->processes/ubus:router.system->processes/g" /etc/config/juci
sed -i "s/ubus:router->clients/ubus:router.network->clients/g" /etc/config/juci
sed -i "s/ubus:router->leases/ubus:router.network->leases/g" /etc/config/juci
sed -i "s/ubus:router->stas/ubus:router.wireless->stas/g" /etc/config/juci
sed -i "s/ubus:router->dslstats/ubus:router.dsl->stats/g" /etc/config/juci
sed -i "s/ubus:router->igmptable/ubus:router.net->igmp_snooping/g" /etc/config/juci
sed -i "s/ubus:router->usb/ubus:router.usb->status/g" /etc/config/juci
sed -i "s/ubus:router->logs/ubus:router.system->logs/g" /etc/config/juci
sed -i "s/ubus:wps/ubus:router.wps/g" /etc/config/juci

curtheme="$(uci -q get juci.juci.theme)"
themexst="$(opkg list ${curtheme:-NOTHEME})"
[ -n "$curtheme" -a -n "$themexst" ] || {
	theme="$(opkg list | grep juci-theme | head -1 | awk '{print$1}')"
	theme=${theme:-juci-theme-inteno}
	uci -q set juci.juci.theme="$theme"
}

routermodel="$(db get hw.board.iopVersion | cut -d'-' -f1)"
case "$routermodel" in
	EX400)
		defmode="$(uci -c /rom/etc/config/ -q get netmode.setup.curmode)"
		curmode="$(uci -q get netmode.setup.curmode)"
		[ "$curmode" == "$defmode" ] && uci -q set juci.juci.homepage="netmode-wizard"
	;;
esac

#wikiver="$(db get hw.board.iopVersion | awk -F'[_,-]' '{print$3}' | tr -d 'A-Z' | awk -F'.' '{print$1$2}')"
wikiver="v311"

uci -q get juci.wiki || {
	uci -q set juci.wiki=wiki
	uci -q set juci.wiki.visible=0
	uci -q set juci.wiki.version=$wikiver
}

uci commit juci

uci -q get juci.@widget[0] || {
cat >> /etc/config/juci << EOF
config widget
	list name overviewWidget99Clientmode
	list name overviewStatusWidget99Netmode
	list name overviewWidget90Netmode

config widget
	list name overviewWidget11WAN
	list name overviewStatusWidget11WAN
	list name overviewWidget10Network
	list name overviewStatusWidget10Network
	list name overviewSliderWidget10Network
	list name overviewStatusWidget01Ethernet
	option link "#!/internet-ethernet"

config widget
	list name overviewWidget40Voice
	list name overviewStatusWidget40Voice
	option link "#!/voice-call-log"
	option require "asterisk.status"

config widget
	list name overviewWidget00WiFi
	list name overviewStatusWidget00WiFi
	option link "#!/wireless-status"

config widget
	list name overviewWidget20USB
	list name overviewStatusWidget20USB
	option link "#!/status-usb"

config widget
	list name overviewStatusWidget99OnlineUpgrade

EOF
}

grep -qw "config juci 'juci'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config juci 'juci'
	option homepage 'overview'

EOF
}

grep -qw "config login 'login'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config login 'login'
	option showusername '1'
	option defaultuser 'user'

EOF
}

grep -qw "config localization 'localization'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config localization 'localization'
	option default_language 'en'
	list languages 'en'

EOF
}

grep -qw "config pagesystemstatus 'pagesystemstatus'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config pagesystemstatus 'pagesystemstatus'

EOF
}

grep -qw "config juci_event 'juci_event'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config juci_event 'juci_event'
	list filter firewall.ssh
	list filter network.netifd
	list filter network.dnmasq
	list filter system.kernel
	list filter system.ntp
	list filter iptv.mcpd

EOF
}

grep -qw "option page 'netmode-wizard'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'netmode-wizard'
	option page 'netmode-wizard'
	option hidden '1'

EOF
}

grep -qw "option page 'overview'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'overview'
	option page 'overview'

EOF
}

grep -qw "option page 'voice'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice'
	option page 'voice'
	option redirect 'first'
	list acls 'juci-inteno-voice-client'
	list require 'file:/etc/config/voice_client'
	#list require 'ubus:asterisk'

EOF
}

grep -qw "option page 'voice-call-log'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/call-log'
	option page 'voice-call-log'
	list acls 'juci-inteno-voice-client'
	list require 'ubus:asterisk.call_log'

EOF
}

grep -qw "option page 'voice-sip-accounts'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/sip-accounts'
	option page 'voice-sip-accounts'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-sip-users'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/sip-users'
	option page 'voice-sip-users'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-lines'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/lines'
	option page 'voice-lines'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-advanced-settings'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/advanced-settings'
	option page 'voice-advanced-settings'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option redirect 'first'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-advanced-settings-sip'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/advanced-settings/sip'
	option page 'voice-advanced-settings-sip'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-advanced-settings-lines'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/advanced-settings/lines'
	option page 'voice-advanced-settings-lines'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-advanced-settings-dialplan'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/advanced-settings/dialplan'
	option page 'voice-advanced-settings-dialplan'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-number-blocking'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/number-blocking'
	option page 'voice-number-blocking'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-ringing-schedule'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/ringing-schedule'
	option page 'voice-ringing-schedule'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-speed-dialing'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/speed_dialing'
	option page 'voice-speed-dialing'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

EOF
}

grep -qw "option page 'voice-dect'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'voice/dect'
	option page 'voice-dect'
	list acls 'juci-natalie-dect'
	list require 'file:/etc/config/dect'
	list require 'ubus:dect'

EOF
}

grep -qw "option page 'network'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet'
	option page 'network'
	option redirect 'first'

EOF
}

grep -qw "option page 'internet-ethernet'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet'
	option page 'internet-ethernet'
	list acls 'juci-network-netifd'
	list require 'ubus:network.device'

EOF
}

grep -qw "option page 'page-broadcom-ethernet-phy'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet/phy'
	option page 'page-broadcom-ethernet-phy'
	list acls 'juci-broadcom-ethernet'
	list acls 'user-support'
	list require 'file:/etc/config/layer2_interface_ethernet'
	list require 'file:/etc/config/ports'

EOF
}

grep -qw "option page 'page-broadcom-adsl'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet/adsl'
	option page 'page-broadcom-adsl'
	list acls 'juci-broadcom-dsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface_adsl'

EOF
}

grep -qw "option page 'page-broadcom-vdsl'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet/vdsl'
	option page 'page-broadcom-vdsl'
	list acls 'juci-broadcom-dsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface_vdsl'

EOF
}

grep -qw "option page 'page-broadcom-ethernet-vlan'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet/vlan'
	option page 'page-broadcom-ethernet-vlan'
	list acls 'juci-broadcom-vlan'
	list acls 'user-support'
	list require 'file:/etc/config/layer2_interface_vlan'

EOF
}

grep -qw "option page 'network-xdsl'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/xdsl'
	option page 'network-xdsl'
	list acl 'juci-broadcom-xdsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface'

EOF
}

grep -qw "option page 'internet-network'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/network'
	option page 'internet-network'
	list acls 'juci-network-netifd'
	list acls 'user-support'
	list require 'file:/etc/config/network'

EOF
}

grep -qw "option page 'internet-routes'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/routes'
	option page 'internet-routes'
	list acls 'juci-network-netifd'
	list acls 'user-support'
	list require 'file:/etc/config/network'

EOF
}

grep -qw "option page 'internet-firewall'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/firewall'
	option page 'internet-firewall'
	list acls 'juci-firewall-fw3'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'internet-firewall-zones'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/firewall/zones'
	option page 'internet-firewall-zones'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'internet-firewall-rules'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/firewall/rules'
	option page 'internet-firewall-rules'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'internet-firewall-port-mapping'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/firewall/port_mapping'
	option page 'internet-firewall-port-mapping'
	list acls 'juci-firewall-fw3'
	option modes 'expert'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'internet-firewall-dmz'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/firewall/dmz'
	option page 'internet-firewall-dmz'
	list acls 'juci-firewall-fw3'
	option modes 'expert'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'internet-parental-control'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/parental_control'
	option page 'internet-parental-control'
	list acls 'juci-firewall-fw3'
	list require 'file:/etc/config/firewall'

EOF
}

grep -qw "option page 'juci-inteno-qos'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/qos'
	option page 'juci-inteno-qos'
	list acls 'juci-inteno-qos'
	list acls 'user-support'
	list require 'file:/etc/config/qos'

EOF
}

grep -qw "option page 'internet-multiwan'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/multiwan'
	option page 'internet-multiwan'
	list acls 'juci-inteno-multiwan'
	list acls 'user-support'
	list require 'file:/etc/config/multiwan'


grep -qw "option page 'internet-mwan3'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/mwan3'
	option page 'internet-mwan3'
	list acls 'juci-mwan3'
	list acls 'user-support'
	list require 'file:/etc/config/mwan3'

EOF
}

grep -qw "option page 'internet-services'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services'
	option page 'internet-services'
	list acls 'juci-network-netifd'

EOF
}

grep -qw "option page 'internet-services-printer'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/printer'
	option page 'internet-services-printer'
	list acls 'juci-printer'
	list require 'file:/etc/config/p910nd'

EOF
}

grep -qw "option page 'internet-services-minidlna'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/minidlna'
	option page 'internet-services-minidlna'
	list acls 'juci-minidlna'
	list require 'file:/etc/config/minidlna'

EOF
}

grep -qw "option page 'upnpd-settings'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/upnp'
	option page 'upnpd-settings'
	list acls 'juci-upnp'
	list require 'file:/etc/config/upnpd'

EOF
}

grep -qw "option page 'internet-services-ddns'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/ddns'
	option page 'internet-services-ddns'
	list acls 'juci-ddns'
	list require 'file:/etc/config/ddns'

EOF
}

grep -qw "option page 'broadcom-iptv'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/mcpd'
	option page 'broadcom-iptv'
	list acls 'juci-broadcom-iptv'
	list acls 'user-support'
	list require 'file:/etc/config/mcpd'

EOF
}

grep -qw "option page 'dhcp-settings'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu 
	option path 'internet/services/dhcp'
	option page 'dhcp-settings'
	list acls 'juci-dnsmasq-dhcp'
	list acls 'user-support'
	list require 'file:/etc/config/dhcp'

EOF
}

grep -qw "option page 'snmpd-config'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu 
	option path 'internet/services/snmpd'
	option page 'snmpd-config'
	list acls 'juci-snmpd'
	list acls 'user-support'
	list require 'file:/etc/config/snmpd'

EOF
}

grep -qw "option page 'internet-services-samba'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'internet/services/samba'
	option page 'internet-services-samba'
	list acls 'juci-samba'
	list require 'file:/etc/config/samba'

EOF
}

grep -qw "option page 'wireless'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi'
	option page 'wireless'
	option redirect 'first'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-general'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/general'
	option page 'wireless-general'
	option redirect 'wireless-interfaces'
	list acls 'juci-wireless'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-devices'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/general/devices'
	option page 'wireless-devices'
	list acls 'juci-wireless'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-interfaces'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/general/interfaces'
	option page 'wireless-interfaces'
	list acls 'juci-wireless'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-schedule'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
#config menu
#       option path 'wifi/schedule'
#       option page 'wireless-schedule'
#       list acls 'juci-wireless'
#	list require 'file:/etc/config/wireless'
EOF
}

grep -qw "option page 'wireless-band-steering'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
        option path 'wifi/band_steering'
	option page 'wireless-band-steering'
	list acls 'juci-wireless'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-wps'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/wps'
	option page 'wireless-wps'
	list acls 'juci-wireless'
	list require 'file:/etc/config/wireless'
	list require 'ubus:wps'

EOF
}

grep -qw "option page 'wireless-filtering'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/mac_filter'
	option page 'wireless-filtering'
	list acls 'juci-wireless'
	option modes 'expert'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'wireless-client-mode'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'wifi/client'
	option page 'wireless-client-mode'
	list acls 'juci-wireless'
	list acls 'not-used'
	list require 'file:/etc/config/wireless'

EOF
}

grep -qw "option page 'system'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings'
	option page 'system'
	option redirect 'first'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-system'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/system'
	option page 'settings-system'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-system-timeservers'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/system/timeservers'
	option page 'settings-system-timeservers'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-system-log'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/system/log'
	option page 'settings-system-log'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-connectivity-test'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/system/connectivity'
	option page 'settings-connectivity-test'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-users'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/users'
	option page 'settings-users'
	list acls 'user-admin'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/juci'

EOF
}

grep -qw "option page 'settings-password'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/password'
	option page 'settings-password'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/passwords'

EOF
}

grep -qw "option page 'settings-upgrade'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/upgrade'
	option page 'settings-upgrade'
	list acls 'juci-sysupgrade'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-upgrade-options'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/upgrade/options'
	option page 'settings-upgrade-options'
	list acls 'juci-sysupgrade'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-configuration'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/configuration'
	option page 'settings-configuration'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'inteno-backup-settings'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/configuration/settings'
	option page 'inteno-backup-settings'
	list acls 'juci-inteno-backup'
	list acls 'user-support'
	list require 'file:/etc/config/backup'

EOF
}

grep -qw "option page 'settings-provisioning-iup'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/provisioning'
	option page 'settings-provisioning-iup'
	list acls 'juci-inteno-provisioning'
	list acls 'user-support'
	list require 'file:/etc/config/provisioning'

EOF
}

grep -qw "option page 'icwmp-config'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/icwmp'
	option page 'icwmp-config'
	list acls 'juci-icwmp'
	list acls 'user-support'
	list require 'file:/etc/config/cwmp'

EOF
}

grep -qw "option page 'settings-management'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/management'
	option page 'settings-management'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

EOF
}

grep -qw "option page 'settings-management-owsd'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/management/owsd'
	option page 'settings-management-owsd'
	list acls 'juci-owsd'
	list require 'file:/etc/config/owsd'

EOF
}

grep -qw "option page 'settings-management-catv'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu 
	option path 'settings/management/catv'
	option page 'settings-management-catv'
	list acls 'juci-catv'
	list acls 'user-support'
	list require 'file:/etc/config/catv'

EOF
}

grep -qw "option page 'settings-management-dropbear'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/management/dropbear'
	option page 'settings-management-dropbear'
	list acls 'juci-dropbear'
	list acls 'user-support'
	list require 'file:/etc/config/dropbear'

EOF
}

grep -qw "option page 'page-uhttpd-settings'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/management/uhttpd'
	option page 'page-uhttpd-settings'
	list acls 'juci-uhttpd'
	list acls 'user-support'
	list require 'file:/etc/config/uhttpd'

EOF
}

grep -qw "option page 'settings-hardware'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/hardware'
	option page 'settings-hardware'
	option redirect 'first'
	list require 'file:/etc/config/buttons'
	list require 'file:/etc/config/leds'

EOF
}

grep -qw "option page 'settings-hardware-buttons'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/hardware/buttons'
	option page 'settings-hardware-buttons'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/buttons'

EOF
}

grep -qw "option page 'settings-hardware-leds'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/hardware/leds'
	option page 'settings-hardware-leds'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/leds'

EOF
}

grep -qw "option page 'broadcom-pwrmgmt'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/pwrmgmt'
	option page 'broadcom-pwrmgmt'
	list acls 'juci-broadcom-pwrmgmt'
	list acls 'user-support'
	list require 'file:/etc/config/power_mgmt'

EOF
}

grep -qw "option page 'settings-services'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/services'
	option page 'settings-services'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'ubus:service'

EOF
}

grep -qw "option page 'settings-restart'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'settings/restart'
	option page 'settings-restart'
	list require 'ubus:juci.system'

EOF
}

grep -qw "option page 'status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status'
	option page 'status'
	option redirect 'first'

EOF
}

grep -qw "option page 'status-system'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/system'
	option page 'status-system'
	list acls 'juci-mod-system'
	list require 'ubus:router.system->info'

EOF
}

grep -qw "option page 'status-system-processes'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/system/processes'
	option page 'status-system-processes'
	list acls 'juci-mod-system'
	list require 'ubus:router.system->processes'

EOF
}

grep -qw "option page 'status-network'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/network'
	option page 'status-network'
	list acls 'juci-network-netifd'
	list require 'ubus:network.interface'

EOF
}

grep -qw "option page 'netifd-status-clients'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/network/clients'
	option page 'netifd-status-clients'
	list acls 'juci-network-netifd'
	list require 'ubus:router.network->clients'

EOF
}

grep -qw "option page 'status-network-routes'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/network/routes'
	option page 'status-network-routes'
	list acls 'juci-network-netifd'
	list require 'ubus:router.net'

EOF
}

grep -qw "option page 'upnpd-status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/network/upnpd'
	option page 'upnpd-status'
	list acls 'juci-upnp'
	list require 'ubus:juci.upnpd'

EOF
}

grep -qw "option page 'dhcp-status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu 
	option path 'status/network/dhcp'
	option page 'dhcp-status'
	list acls 'juci-dnsmasq-dhcp'
	list require 'ubus:router.network->leases'

EOF
}

grep -qw "option page 'status-network-nat'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/network/nat'
	option page 'status-network-nat'
	list acls 'juci-network-netifd'
	list require 'ubus:router.net'

EOF
}

grep -qw "option page 'wireless-status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/wifi'
	option page 'wireless-status'
	list acls 'juci-wireless'
	list require 'ubus:router.wireless->stas'

EOF
}

grep -qw "option page 'wireless-status-scan'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/wifi/scan'
	option page 'wireless-status-scan'
	list acls 'juci-wireless'
	list require 'ubus:router.wireless'

EOF
}

grep -qw "option page 'wireless-band-steering-status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/wifi/bandsteering'
	option page 'wireless-band-steering-status'
	list acls 'juci-wireless'
	list acls 'user-admin'
	list require 'ubus:juci.wireless'

EOF
}

grep -qw "option page 'page-broadcom-dsl-status'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/dsl'
	option page 'page-broadcom-dsl-status'
	list acls 'juci-broadcom-dsl'
	list require 'file:/etc/dsl'
	#list require 'ubus:router.dsl->stats'

EOF
}

grep -qw "option page 'status-tv'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/tv'
	option page 'status-tv'
	list acls 'juci-igmpinfo'
	list require 'ubus:router.net->igmp_snooping'

EOF
}

grep -qw "option page 'status-usb'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/usb'
	option page 'status-usb'
	list acls 'juci-usb'
	list require 'ubus:router.usb->status'

EOF
}

grep -qw "option page 'status-catv'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/catv'
	option page 'status-catv'
	list acls 'juci-catv'
	list require 'ubus:catv'

EOF
}

grep -qw "option page 'status-sfp'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/sfp'
	option page 'status-sfp'
	list acls 'juci-sfp'
	list require 'ubus:sfp.ddm'
	list require 'ubus:sfp.rom'

EOF
}

grep -qw "option page 'status-diagnostics'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/diagnostics'
	option page 'status-diagnostics'
	list acls 'juci-diagnostics'
	list require 'ubus:juci.diagnostics'

EOF
}

grep -qw "option page 'status-diagnostics-speedtest'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/diagnostics/speedtest'
	option page 'status-diagnostics-speedtest'
	list acls 'juci-diagnostics'
	list require 'ubus:juci.speedtest'

EOF
}

grep -qw "option page 'status-phone'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/phone'
	option page 'status-phone'
	list acls 'juci-inteno-voice-client'
	list require 'ubus:asterisk'

EOF
}

grep -qw "option page 'status-events'" /etc/config/juci || {
cat >> /etc/config/juci << EOF
config menu
	option path 'status/events'
	option page 'status-events'
	option modes 'expert'
	list acls 'user-support'
	list require 'ubus:log'
	list require 'ubus:router.system->logs'
EOF
}

grep -q juci /etc/config/rpcd || {
cat > /etc/config/rpcd << EOF
config login
	option username 'admin'
	option password '\$p\$admin'
	list write 'user-admin'
	list write 'user-support'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-wireless'
	list write 'juci-wireless-admin'
	list write 'juci-broadcom-xdsl'
	list write 'juci-catv'
	list write 'juci-broadcom-pwrmgmt'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-icwmp'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-mod-system-admin'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'support'
	option password '\$p\$support'
	list write 'user-support'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-wireless'
	list write 'juci-wireless-admin'
	list write 'juci-broadcom-xdsl'
	list write 'juci-broadcom-pwrmgmt'
	list write 'juci-catv'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-icwmp'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'user'
	option password '\$p\$user'
	list write 'user-user'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-wireless'
	list write 'juci-wireless-admin'
	list write 'juci-catv'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'
EOF
}

exit 0
