#!/bin/sh

grep -q menu /etc/config/juci || {
cat > /etc/config/juci << EOF
config juci 'juci'
	option homepage 'overview'

config login 'login'
	option showusername '1'
	option defaultuser 'user'

config localization 'localization'
	option default_language 'en'
	list languages 'en'

config pagesystemstatus 'pagesystemstatus'

config juci_event 'juci_event'
	list filter firewall.ssh
	list filter network.netifd
	list filter network.dnmasq
	list filter system.kernel
	list filter system.ntp
	list filter iptv.mcpd

config menu
	option path 'overview'
	option page 'overview'

config menu
	option path 'voice'
	option redirect 'first'
	list acls 'juci-inteno-voice-client'
	list require 'file:/etc/config/voice_client'
	#list require 'ubus:asterisk'

config menu
	option path 'voice/log'
	option page 'voice-log'
	list acls 'juci-inteno-voice-client'
	list require 'ubus:asterisk.call_log'

config menu
	option path 'voice/accounts'
	option page 'voice-accounts'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/users'
	option page 'voice-users'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/lines'
	option page 'voice-lines'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/advanced'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	option redirect 'first'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/advanced/sip'
	option page 'voice-advanced-sip'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/advanced/lines'
	option page 'voice-advanced-line'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/advanced/dialplan'
	option page 'voice-advanced-dialplan'
	list acls 'juci-inteno-voice-client'
	list acls 'user-support'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/blocking'
	option page 'voice-blocking'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/schedule'
	option page 'voice-schedule'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/dialing'
	option page 'voice-dialing'
	list acls 'juci-inteno-voice-client'
	option modes 'expert'
	list require 'file:/etc/config/voice_client'

config menu
	option path 'voice/dect'
	option page 'voice-dect'
	list acls 'juci-natalie-dect'
	list require 'file:/etc/config/dect'
	list require 'ubus:dect'

config menu
	option path 'network'
	option redirect 'first'

config menu
	option path 'network/devices'
	option page 'network-devices'
	list acls 'juci-network-netifd'
	list require 'ubus:/juci/network'

config menu
	option path 'network/devices/ethernet'
	option page 'network-devices-ethernet'
	list acls 'juci-broadcom-ethernet'
	list acls 'user-support'
	list require 'file:/etc/config/layer2_interface_ethernet'
	list require 'file:/etc/config/ports'

config menu
	option path 'network/devices/adsl'
	option page 'network-devices-adsl'
	list acls 'juci-broadcom-dsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface_adsl'

config menu
	option path 'network/devices/vdsl'
	option page 'network-devices-vdsl'
	list acls 'juci-broadcom-dsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface_vdsl'

config menu
	option path 'network/devices/vlan'
	option page 'network-devices-vlan'
	list acls 'juci-broadcom-vlan'
	list acls 'user-support'
	list require 'file:/etc/config/layer2_interface_vlan'

config menu
	option path 'network/xdsl'
	option page 'network-xdsl'
	list acl 'juci-broadcom-xdsl'
	list acls 'user-support'
	list require 'file:/etc/dsl'
	list require 'file:/etc/config/layer2_interface'

config menu
	option path 'network/connections'
	option page 'network-connections'
	list acls 'juci-network-netifd'
	list acls 'user-support'
	list require 'file:/etc/config/network'

config menu
	option path 'network/routes'
	option page 'network-routes'
	list acls 'juci-network-netifd'
	list acls 'user-support'
	list require 'file:/etc/config/network'

config menu
	option path 'network/firewall'
	option page 'network-firewall'
	list acls 'juci-firewall-fw3'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/firewall/zones'
	option page 'network-firewall-zones'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/firewall/rules'
	option page 'network-firewall-rules'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/firewall/forwarding'
	option page 'network-firewall-forwarding'
	list acls 'juci-firewall-fw3'
	option modes 'expert'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/firewall/dmz'
	option page 'network-firewall-dmz'
	list acls 'juci-firewall-fw3'
	option modes 'expert'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/parental'
	option page 'network-parental'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'
	list require 'file:/etc/config/firewall'

config menu
	option path 'network/qos'
	option page 'network-qos'
	list acls 'network-qos'
	list acls 'user-support'
	list require 'file:/etc/config/qos'

config menu
	option path 'network/multiwan'
	option page 'network-multiwan'
	list acls 'juci-inteno-multiwan'
	list acls 'user-support'
	list require 'file:/etc/config/multiwan'

config menu
	option path 'network/services'
	option page 'network-services'
	list acls 'juci-network-netifd'

config menu
	option path 'network/services/printer'
	option page 'network-services-printer'
	list acls 'juci-printer'
	list require 'file:/etc/config/p910nd'

config menu
	option path 'network/services/minidlna'
	option page 'network-services-minidlna'
	list acls 'juci-minidlna'
	list require 'file:/etc/config/minidlna'

config menu
	option path 'network/services/upnp'
	option page 'network-services-upnp'
	list acls 'juci-upnp'
	list acls 'user-support'
	list require 'file:/etc/config/upnpd'

config menu
	option path 'network/services/ddns'
	option page 'network-services-ddns'
	list acls 'juci-ddns'
	list acls 'user-support'
	list require 'file:/etc/config/ddns'

config menu
	option path 'network/services/iptv'
	option page 'network-services-iptv'
	list acls 'juci-broadcom-iptv'
	list acls 'user-support'
	list require 'file:/etc/config/mcpd'

config menu 
	option path 'network/services/dhcp'
	option page 'network-services-dhcp'
	list acls 'juci-dnsmasq-dhcp'
	list acls 'user-support'
	list require 'file:/etc/config/dhcp'

config menu 
	option path 'network/services/snmp'
	option page 'network-services-snmp'
	list acls 'juci-snmpd'
	list acls 'user-support'
	list require 'file:/etc/config/snmpd'

config menu
	option path 'network/services/samba'
	option page 'network-services-samba'
	list acls 'juci-samba'
	list require 'file:/etc/config/samba'

config menu
	option path 'wifi'
	option redirect 'first'
	list require 'file:/etc/config/wireless'

config menu
	option path 'wifi/general'
	option redirect 'wifi-general-wireless'
	list acls 'juci-broadcom-wl'
	list require 'file:/etc/config/wireless'

config menu
	option path 'wifi/general/radios'
	option page 'wifi-general-radios'
	list acls 'juci-broadcom-wl'
	list require 'file:/etc/config/wireless'

config menu
	option path 'wifi/general/wireless'
	option page 'wifi-general-wireless'
	list acls 'juci-broadcom-wl'
	list require 'file:/etc/config/wireless'

#config menu
#       option path 'wifi/schedule'
#       option page 'wifi-schedule'
#       list acls 'juci-broadcom-wl'
#	list require 'file:/etc/config/wireless'

config menu
	option path 'wifi/wps'
	option page 'wifi-wps'
	list acls 'juci-broadcom-wl'
	list require 'file:/etc/config/wireless'
	list require 'ubus:wps'

config menu
	option path 'wifi/mac'
	option page 'wifi-mac'
	list acls 'juci-broadcom-wl'
	option modes 'expert'
	list require 'file:/etc/config/wireless'

config menu
	option path 'system'
	option page 'system'
	option redirect 'first'
	list require 'file:/etc/config/system'

config menu
	option path 'system/settings'
	option page 'system-settings'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/system'

config menu
	option path 'system/settings/timeservers'
	option page 'system-settings-timeservers'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/system'

config menu
	option path 'system/settings/log'
	option page 'system-settings-log'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

config menu
	option path 'system/menu'
	option page 'system-menu'
	list acls 'user-admin'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/juci'

config menu
	option path 'system/password'
	option page 'system-password'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/passwords'

config menu
	option path 'system/firmware'
	option page 'system-firmware'
	list acls 'juci-sysupgrade'
	list acls 'user-support'
	list require 'file:/etc/config/system'

config menu
	option path 'system/firmware/options'
	option page 'system-firmware-options'
	list acls 'juci-sysupgrade'
	list acls 'user-support'
	list require 'file:/etc/config/system'

config menu
	option path 'system/restore'
	option page 'system-restore'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

config menu
	option path 'system/restore/settings'
	option page 'system-restore-settings'
	list acls 'juci-inteno-backup'
	list acls 'user-support'
	list require 'file:/etc/config/backup'

config menu
	option path 'system/iup'
	option page 'system-iup'
	list acls 'juci-inteno-provisioning'
	list acls 'user-support'
	list require 'file:/etc/config/provisioning'

config menu
	option path 'system/tr69'
	option page 'system-tr69'
	list acls 'juci-icwmp'
	list acls 'user-support'
	list require 'file:/etc/config/cwmp'

config menu 
	option path 'system/catv'
	option page 'system-catv'
	list acls 'juci-catv'
	list acls 'user-support'
	list require 'file:/etc/config/catv'

config menu
	option path 'system/management'
	option page 'system-management'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'file:/etc/config/system'

config menu
	option path 'system/management/owsd'
	option page 'system-management-owsd'
	list acls 'juci-owsd'
	list require 'file:/etc/config/owsd'

config menu
	option path 'system/management/ssh'
	option page 'system-management-ssh'
	list acls 'juci-dropbear'
	list acls 'user-support'
	list require 'file:/etc/config/dropbear'

config menu
	option path 'system/management/uhttp'
	option page 'system-management-uhttp'
	list acls 'not-used'
	list acls 'juci-uhttpd'
	list acls 'user-support'
	list require 'file:/etc/config/uhttpd'

config menu
	option path 'system/hardware'
	option page 'system-hardware'
	option redirect 'first'
	list require 'file:/etc/config/buttons'
	list require 'file:/etc/config/leds'

config menu
	option path 'system/hardware/buttons'
	option page 'system-hardware-buttons'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/buttons'

config menu
	option path 'system/hardware/leds'
	option page 'system-hardware-leds'
	list acls 'juci-mod-system'
	list require 'file:/etc/config/leds'

config menu
	option path 'system/power'
	option page 'system-power'
	list acls 'juci-broadcom-pwrmgmt'
	list acls 'user-support'
	list require 'file:/etc/config/power_mgmt'

config menu
	option path 'system/services'
	option page 'system-services'
	list acls 'juci-mod-system'
	list acls 'user-support'
	list require 'ubus:service'

config menu
	option path 'system/restart'
	option page 'system-restart'
	list require 'ubus:/juci/system'

config menu
	option path 'status'
	option redirect 'first'

config menu
	option path 'status/system'
	option page 'status-system'
	list acls 'juci-mod-system'
	list require 'ubus:router->info'

config menu
	option path 'status/system/processes'
	option page 'status-system-processes'
	list acls 'juci-mod-system'
	list require 'ubus:/juci/system.process'

config menu
	option path 'status/network'
	option page 'status-network'
	list acls 'juci-network-netifd'
	list require 'ubus:network.interface'

config menu
	option path 'status/network/clients'
	option page 'status-network-clietns'
	list acls 'juci-network-netifd'
	list require 'ubus:router->clients'

config menu
	option path 'status/network/routing'
	option page 'status-network-routing'
	list acls 'juci-network-netifd'
	list require 'ubus:/juci/network.status'

config menu
	option path 'status/network/upnp'
	option page 'status-network-upnp'
	list acls 'juci-upnp'
	list require 'ubus:/juci/upnpd'

config menu 
	option path 'status/network/dhcp'
	option page 'status-network-dhcp'
	list acls 'juci-dnsmasq-dhcp'
	list require 'ubus:router->leases'

config menu
	option path 'status/network/nat'
	option page 'status-network-nat'
	list acls 'juci-network-netifd'
	list require 'ubus:/juci/network'

config menu
	option path 'status/wifi'
	option redirect 'first'
	list acls 'juci-broadcom-wl'
	list require 'ubus:router->stas'

config menu
	option path 'status/wifi/status'
	option page 'status-wifi-status'
	list acls 'juci-broadcom-wl'
	list require 'ubus:router->stas'

config menu
	option path 'status/wifi/scan'
	option page 'status-wifi-scan'
	list acls 'juci-broadcom-wl'
	list require 'ubus:/juci/wireless'

config menu
	option path 'status/dsl'
	option page 'status-dsl'
	list acls 'juci-broadcom-dsl'
	list require 'file:/etc/dsl'
	#list require 'ubus:router->dslstats'

config menu
	option path 'status/igmp'
	option page 'status-igmp'
	list acls 'juci-igmpinfo'
	list require 'ubus:router->igmptable'

config menu
	option path 'status/usb'
	option page 'status-usb'
	list acls 'juci-usb'
	list require 'ubus:router->usb'

config menu
	option path 'status/catv'
	option page 'status-catv'
	list acls 'juci-catv'
	list require 'ubus:catv'

config menu
	option path 'status/sfp'
	option page 'status-sfp'
	list acls 'juci-sfp'
	list require 'ubus:sfp.ddm'
	list require 'ubus:sfp.rom'

config menu
	option path 'status/diagnostics'
	option page 'status-diagnostics'
	list acls 'juci-diagnostics'
	list require 'ubus:/juci/diagnostics'

config menu
	option path 'status/diagnostics/tp'
	option page 'status-diagnostics-tp'
	list acls 'juci-diagnostics'
	list require 'ubus:/juci/speedtest'

config menu
	option path 'status/voice'
	option page 'status-voice'
	list acls 'juci-inteno-voice-client'
	list require 'ubus:asterisk'

config menu
	option path 'status/log'
	option page 'status-log'
	option modes 'expert'
	list acls 'user-support'
	list require 'ubus:log'
	list require 'ubus:router->logs'
EOF
}

grep -q juci /etc/config/rpcd || {
cat > /etc/config/rpcd << EOF
config login
	option username 'admin'
	option password '\$p\$admin'
	list write 'user-admin'
	list write 'user-support'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-broadcom-wl'
	list write 'juci-broadcom-wl-admin'
	list write 'juci-broadcom-xdsl'
	list write 'juci-catv'
	list write 'juci-broadcom-pwrmgmt'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-icwmp'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-mod-system-admin'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'support'
	option password '\$p\$support'
	list write 'user-support'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-broadcom-wl'
	list write 'juci-broadcom-wl-admin'
	list write 'juci-broadcom-xdsl'
	list write 'juci-broadcom-pwrmgmt'
	list write 'juci-catv'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-icwmp'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'user'
	option password '\$p\$user'
	list write 'user-user'
	list write 'juci-broadcom-dsl'
	list write 'juci-broadcom-dsl-admin'
	list write 'juci-broadcom-ethernet'
	list write 'juci-broadcom-iptv'
	list write 'juci-broadcom-vlan'
	list write 'juci-broadcom-vlan-admin'
	list write 'juci-broadcom-wl'
	list write 'juci-broadcom-wl-admin'
	list write 'juci-catv'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-iconnect'
	list write 'juci-igmpinfo'
	list write 'juci-inteno-backup'
	list write 'juci-inteno-multiwan'
	list write 'juci-inteno-provisioning'
	list write 'juci-inteno-qos'
	list write 'juci-inteno-voice-client'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-natalie-dect'
	list write 'juci-netmode'
	list write 'juci-network-netifd'
	list write 'juci-owsd'
	list write 'juci-printer'
	list write 'juci-samba'
	list write 'juci-sfp'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'
EOF
}

exit 0
